# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "bootstrap", to: "bootstrap.bundle.min.js"
pin "desk", to: "desk.js"
pin "lil-gui"
pin "three", to: "#{THREE_BASE_URL}/build/three.module.js"
pin "three/addons/controls/OrbitControls", to: "#{THREE_ADDONS_URL}/controls/OrbitControls.js"
pin "three/addons/loaders/DRACOLoader", to: "#{THREE_ADDONS_URL}/loaders/DRACOLoader.js"
pin "three/addons/loaders/GLTFLoader", to: "#{THREE_ADDONS_URL}/loaders/GLTFLoader.js"
pin "three/addons/loaders/RGBELoader", to: "#{THREE_ADDONS_URL}/loaders/RGBELoader.js"
pin "three/addons/loaders/FontLoader", to: "#{THREE_ADDONS_URL}/loaders/FontLoader.js"
pin "three/addons/loaders/FBXLoader", to: "#{THREE_ADDONS_URL}/loaders/FBXLoader.js"
pin "three/addons/renderers/CSS2DRenderer", to: "#{THREE_ADDONS_URL}/renderers/CSS2DRenderer.js"
pin "three/addons/renderers/CSS3DRenderer", to: "#{THREE_ADDONS_URL}/renderers/CSS3DRenderer.js"
pin "gsap", to: "https://esm.sh/gsap@3.12"
pin_all_from "app/javascript/Experience", to: "Experience"
